"""Task-adaptive scientific input-modality selection research prototype."""

from autonomous_modality.evaluation import calculate_richness
from autonomous_modality.models import (
    CURRENT_SCHEMA_VERSION,
    AssetAvailability,
    BaselineSelectionResult,
    CandidateFilterResult,
    CraterQuestion,
    CraterQuestionType,
    CraterReference,
    CrossModalInsight,
    CrossModalInsightLevel,
    DataAssetProfile,
    EvaluationScenario,
    ExpectedCrossModalInsight,
    ExpectedRichnessProfile,
    InputDataModality,
    InputSelectionConstraints,
    InputSelectionDecision,
    InputSelectionRequest,
    ModalityExclusion,
    ModalityScore,
    RichnessScores,
    SelectedInputModality,
    SelectionPriority,
    SolutionRichnessAnnotation,
    SpatialCoverage,
)
from autonomous_modality.selection import filter_candidates, select_baseline

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "AssetAvailability",
    "BaselineSelectionResult",
    "CandidateFilterResult",
    "CraterQuestion",
    "CraterQuestionType",
    "CraterReference",
    "CrossModalInsight",
    "CrossModalInsightLevel",
    "DataAssetProfile",
    "EvaluationScenario",
    "ExpectedCrossModalInsight",
    "ExpectedRichnessProfile",
    "InputDataModality",
    "InputSelectionConstraints",
    "InputSelectionDecision",
    "InputSelectionRequest",
    "ModalityExclusion",
    "ModalityScore",
    "RichnessScores",
    "SelectedInputModality",
    "SelectionPriority",
    "SolutionRichnessAnnotation",
    "SpatialCoverage",
    "calculate_richness",
    "filter_candidates",
    "select_baseline",
]
